/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.server;


public class Server {
    public static void main(String[] args) {
     UDPServer server = new UDPServer();
     server.goo1();
    }
}
