/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


public class CLI {
    public static void main(String[] args) {
        UDPCLI cli = new UDPCLI();
        cli.go1();
    }
}
